from __future__ import annotations

FINANCIAL_HEALTH_TAG = "finance-health-check"

FINANCIAL_HEALTH_PERIOD_MONTH = "month"
FINANCIAL_HEALTH_PERIOD_QUARTER = "quarter"
FINANCIAL_HEALTH_PERIOD_YEAR = "year"
FINANCIAL_HEALTH_PERIOD_CUSTOM = "custom"

FINANCIAL_HEALTH_PERIODS = [
    FINANCIAL_HEALTH_PERIOD_MONTH,
    FINANCIAL_HEALTH_PERIOD_QUARTER,
    FINANCIAL_HEALTH_PERIOD_YEAR,
    FINANCIAL_HEALTH_PERIOD_CUSTOM,
]
FINANCIAL_HEALTH_DEFAULT_PERIOD = FINANCIAL_HEALTH_PERIOD_MONTH
FINANCIAL_HEALTH_DEFAULT_CURRENCY = "RUB"

FINANCIAL_HEALTH_LEVEL_EXCELLENT = "excellent"
FINANCIAL_HEALTH_LEVEL_GOOD = "good"
FINANCIAL_HEALTH_LEVEL_WARNING = "warning"
FINANCIAL_HEALTH_LEVEL_RISK = "risk"
FINANCIAL_HEALTH_LEVEL_CRITICAL = "critical"

FINANCIAL_HEALTH_LEVELS = [
    FINANCIAL_HEALTH_LEVEL_CRITICAL,
    FINANCIAL_HEALTH_LEVEL_RISK,
    FINANCIAL_HEALTH_LEVEL_WARNING,
    FINANCIAL_HEALTH_LEVEL_GOOD,
    FINANCIAL_HEALTH_LEVEL_EXCELLENT,
]

FINANCIAL_HEALTH_SCORE_MIN = 0
FINANCIAL_HEALTH_SCORE_MAX = 100

FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_HIGH = "high"
FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_MEDIUM = "medium"
FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_LOW = "low"

FINANCIAL_HEALTH_RECOMMENDATION_PRIORITIES = [
    FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_HIGH,
    FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_MEDIUM,
    FINANCIAL_HEALTH_RECOMMENDATION_PRIORITY_LOW,
]

RECOMMENDATION_INSUFFICIENT_CASHFLOW_DATA = "insufficient_cashflow_data"
RECOMMENDATION_NEGATIVE_NET_BALANCE = "negative_net_balance"
RECOMMENDATION_LOW_SAVINGS_RATE = "low_savings_rate"
RECOMMENDATION_BUDGET_OVER_LIMIT = "budget_over_limit"
RECOMMENDATION_WEAK_EMERGENCY_FUND = "weak_emergency_fund"
RECOMMENDATION_CASH_GAP_RISK = "cash_gap_risk"
RECOMMENDATION_HIGH_PLANNED_PAYMENTS_LOAD = "high_planned_payments_load"
RECOMMENDATION_UNSTABLE_EXPENSES = "unstable_expenses"

MAX_FINANCIAL_HEALTH_RECOMMENDATIONS = 6

METRIC_INCOME_EXPENSE_RATIO = "incomeExpenseRatio"
METRIC_SAVINGS_RATE = "savingsRate"
METRIC_BUDGET_USAGE = "budgetUsage"
METRIC_EMERGENCY_FUND_PROGRESS = "emergencyFundProgress"
METRIC_CASH_GAP_RISK = "cashGapRisk"
METRIC_PLANNED_PAYMENTS_LOAD = "plannedPaymentsLoad"
METRIC_EXPENSE_STABILITY = "expenseStability"

FINANCIAL_HEALTH_METRICS = [
    METRIC_INCOME_EXPENSE_RATIO,
    METRIC_SAVINGS_RATE,
    METRIC_BUDGET_USAGE,
    METRIC_EMERGENCY_FUND_PROGRESS,
    METRIC_CASH_GAP_RISK,
    METRIC_PLANNED_PAYMENTS_LOAD,
    METRIC_EXPENSE_STABILITY,
]

FINANCIAL_HEALTH_METRIC_WEIGHTS = {
    METRIC_INCOME_EXPENSE_RATIO: 20,
    METRIC_SAVINGS_RATE: 18,
    METRIC_BUDGET_USAGE: 18,
    METRIC_EMERGENCY_FUND_PROGRESS: 16,
    METRIC_CASH_GAP_RISK: 12,
    METRIC_PLANNED_PAYMENTS_LOAD: 8,
    METRIC_EXPENSE_STABILITY: 8,
}

FINANCIAL_HEALTH_METRIC_CATEGORIES = {
    METRIC_INCOME_EXPENSE_RATIO: "cashflow",
    METRIC_SAVINGS_RATE: "cashflow",
    METRIC_BUDGET_USAGE: "budget",
    METRIC_EMERGENCY_FUND_PROGRESS: "goals",
    METRIC_CASH_GAP_RISK: "risk",
    METRIC_PLANNED_PAYMENTS_LOAD: "risk",
    METRIC_EXPENSE_STABILITY: "stability",
}
