# Generated by Django 5.2.14 on 2026-05-07 18:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название счёта')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс')),
                ('currency', models.CharField(default='RUB', max_length=3, validators=[django.core.validators.RegexValidator(message='Валюта должна быть указана в формате ISO-кода, например RUB.', regex='^[A-Z]{3}$')], verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Лимит бюджета')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ['-period_start', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Текущая сумма')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок достижения')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Достигнута'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.account', verbose_name='Связанный счёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Финансовая цель',
                'verbose_name_plural': 'Финансовые цели',
                'ordering': ['status', 'deadline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account', verbose_name='Счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-operation_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='idx_account_user'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='idx_account_user_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='idx_account_user_name'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='account_currency_code_format'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='idx_category_user'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='idx_category_user_type'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_active'], name='idx_category_user_active'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name', 'type'], name='idx_category_user_name_type'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_category_name_type_per_user'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['income', 'expense'])), name='category_type_valid'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user'], name='idx_budget_user'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='idx_budget_user_period'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category', 'period_start', 'period_end'], name='idx_budget_user_cat_period'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'is_active'], name='idx_budget_user_active'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('amount_limit__gt', 0)), name='budget_amount_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='budget_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'period_start', 'period_end'), name='unique_budget_category_period_per_user'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user'], name='idx_goal_user'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='idx_goal_user_status'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'deadline'], name='idx_goal_user_deadline'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'account'], name='idx_goal_user_account'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='goal_target_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='goal_current_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'cancelled'])), name='goal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_goal_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='idx_transaction_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'operation_date'], name='idx_transaction_user_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'operation_date'], name='idx_transaction_account_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'operation_date'], name='idx_transaction_category_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type', 'operation_date'], name='idx_transaction_user_type_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='idx_transaction_user_created'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['income', 'expense'])), name='transaction_type_valid'),
        ),
    ]
