# Generated by Django 5.2.14 on 2026-05-07 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.category', verbose_name='Родительская категория'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'parent'], name='idx_category_user_parent'),
        ),
    ]
