# Generated by Django 5.2.14 on 2026-05-08 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_parent_category_idx_category_user_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='category_parent_not_self'),
        ),
    ]
