# Generated by Django 5.2.14 on 2026-05-15 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_category_parent_not_self'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_account_date',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_category_date',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='idx_tx_user_type_date',
            old_name='idx_transaction_user_type_date',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='idx_tx_user_created',
            old_name='idx_transaction_user_created',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account', 'operation_date'], name='idx_tx_user_acct_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'operation_date'], name='idx_tx_user_cat_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'amount'], name='idx_tx_user_amount'),
        ),
    ]
