# Generated by Django 5.2.14 on 2026-05-15 18:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_transaction_idx_transaction_account_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'parent_id', 'sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть указан в HEX-формате, например #4F46E5.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивная'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранная'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_archived'], name='idx_cat_user_archived'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_cat_user_favorite'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'parent', 'sort_order'], name='idx_cat_user_type_parent_order'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('color__regex', '^#[0-9A-Fa-f]{6}$')), name='category_color_hex_format'),
        ),
    ]
