# Generated by Django 5.2.14 on 2026-05-15 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_category_options_category_color_category_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'name'], name='idx_cat_user_type_name'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'is_active', 'is_archived', 'is_favorite'], name='idx_cat_user_type_flags'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'parent', 'is_active', 'is_archived', 'is_favorite', 'sort_order'], name='idx_cat_tree_flags_order'),
        ),
    ]
