# Generated by Django 5.2.14 on 2026-05-19

import datetime

import apps.finance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_type_valid",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("operation", "Операции"),
                    ("goal", "Цели"),
                    ("budget", "Бюджет"),
                    ("system", "Система"),
                    ("security", "Безопасность"),
                    ("marketing", "Маркетинг и акции"),
                ],
                default="system",
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="In-app уведомления включены",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email уведомления включены",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Push уведомления включены",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="SMS уведомления включены",
                    ),
                ),
                (
                    "operation_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Уведомления по операциям включены",
                    ),
                ),
                (
                    "goal_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Уведомления по целям включены",
                    ),
                ),
                (
                    "budget_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Уведомления по бюджетам включены",
                    ),
                ),
                (
                    "system_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Системные уведомления включены",
                    ),
                ),
                (
                    "security_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Уведомления безопасности включены",
                    ),
                ),
                (
                    "marketing_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Маркетинговые уведомления включены",
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Тихие часы включены",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default=datetime.time(22, 0),
                        verbose_name="Начало тихих часов",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        verbose_name="Окончание тихих часов",
                    ),
                ),
                (
                    "quiet_hours_days",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_quiet_hours_days,
                        verbose_name="Дни тихих часов",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
                "ordering": ["user_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "operation",
                            "goal",
                            "budget",
                            "system",
                            "security",
                            "marketing",
                        ],
                    )
                ),
                name="notification_type_valid",
            ),
        ),
    ]