# Generated by Django 5.2.14 on 2026-05-20

import decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_notification_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        verbose_name="Название регулярной операции",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                        ],
                        default="expense",
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("0.01")
                            )
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("yearly", "Ежегодно"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="День месяца",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "has_end",
                    models.BooleanField(
                        default=False,
                        verbose_name="Есть дата окончания",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "next_charge_date",
                    models.DateField(
                        verbose_name="Дата следующего списания",
                    ),
                ),
                (
                    "last_charge_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего списания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("paused", "На паузе"),
                            ("completed", "Завершена"),
                            ("error", "Ошибка"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID шаблона",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Название шаблона",
                    ),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Количество созданных операций",
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Код последней ошибки",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        verbose_name="Сообщение последней ошибки",
                    ),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последней ошибки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_transactions",
                        to="finance.account",
                        verbose_name="Счёт",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_transactions",
                        to="finance.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регулярная операция",
                "verbose_name_plural": "Регулярные операции",
                "ordering": ["next_charge_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTransactionCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "charged_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата попытки списания",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        verbose_name="Плановая дата списания",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("0.01")
                            )
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Выполнено"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущено"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="Статус списания",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Код ошибки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        verbose_name="Сообщение ошибки",
                    ),
                ),
                (
                    "recurring_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="finance.recurringtransaction",
                        verbose_name="Регулярная операция",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_charges",
                        to="finance.transaction",
                        verbose_name="Созданная операция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transaction_charges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История регулярного списания",
                "verbose_name_plural": "История регулярных списаний",
                "ordering": ["-charged_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="rtx_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["income", "expense"])),
                name="rtx_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__in", ["daily", "weekly", "monthly", "yearly"])),
                name="rtx_frequency_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "paused", "completed", "error"])),
                name="rtx_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("day_of_month__isnull", True))
                    | (
                        models.Q(("day_of_month__gte", 1))
                        & models.Q(("day_of_month__lte", 31))
                    )
                ),
                name="rtx_day_of_month_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("has_end", False))
                    | models.Q(("end_date__gte", models.F("start_date")))
                ),
                name="rtx_date_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransactioncharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="rtx_charge_amount_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransactioncharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["success", "failed", "skipped"])),
                name="rtx_charge_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user"], name="idx_rtx_user"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "status"], name="idx_rtx_user_status"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "frequency"], name="idx_rtx_user_freq"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "account"], name="idx_rtx_user_account"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "category"], name="idx_rtx_user_category"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "next_charge_date"], name="idx_rtx_user_next"),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["user", "status", "next_charge_date"], name="idx_rtx_status_next"),
        ),
        migrations.AddIndex(
            model_name="recurringtransactioncharge",
            index=models.Index(fields=["user"], name="idx_rtx_charge_user"),
        ),
        migrations.AddIndex(
            model_name="recurringtransactioncharge",
            index=models.Index(fields=["recurring_transaction"], name="idx_rtx_charge_rtx"),
        ),
        migrations.AddIndex(
            model_name="recurringtransactioncharge",
            index=models.Index(fields=["user", "status"], name="idx_rtx_charge_status"),
        ),
        migrations.AddIndex(
            model_name="recurringtransactioncharge",
            index=models.Index(fields=["user", "charged_at"], name="idx_rtx_charge_date"),
        ),
        migrations.AddIndex(
            model_name="recurringtransactioncharge",
            index=models.Index(fields=["transaction"], name="idx_rtx_charge_tx"),
        ),
    ]
