# Generated by Django 5.2.14 on 2026-05-20

import decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_recurring_transactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        verbose_name="Название плановой операции",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                        ],
                        default="expense",
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("0.01"),
                            ),
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        verbose_name="Плановая дата операции",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("confirmed", "Подтверждена"),
                            ("cancelled", "Отменена"),
                            ("converted", "Конвертирована"),
                            ("overdue", "Просрочена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "include_in_forecast",
                    models.BooleanField(
                        default=True,
                        verbose_name="Учитывать в прогнозе баланса",
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата конвертации",
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Код последней ошибки",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        verbose_name="Сообщение последней ошибки",
                    ),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последней ошибки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_transactions",
                        to="finance.account",
                        verbose_name="Счёт",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_transactions",
                        to="finance.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "converted_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_planned_transaction",
                        to="finance.transaction",
                        verbose_name="Созданная операция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Планируемая операция",
                "verbose_name_plural": "Планируемые операции",
                "ordering": ["planned_date", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="plannedtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ptx_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["income", "expense"])),
                name="ptx_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "confirmed",
                            "cancelled",
                            "converted",
                            "overdue",
                        ],
                    ),
                ),
                name="ptx_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user"], name="idx_ptx_user"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "status"], name="idx_ptx_user_status"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "planned_date"], name="idx_ptx_user_date"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "account"], name="idx_ptx_user_account"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "category"], name="idx_ptx_user_category"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "include_in_forecast"], name="idx_ptx_user_forecast"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["user", "status", "planned_date"], name="idx_ptx_status_date"),
        ),
        migrations.AddIndex(
            model_name="plannedtransaction",
            index=models.Index(fields=["converted_transaction"], name="idx_ptx_converted_tx"),
        ),
    ]
