# Generated by ChatGPT for BUD-1095 on 2026-05-21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_planned_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="category_group",
            field=models.CharField(
                choices=[
                    ("main", "Основной бюджет"),
                    ("family", "Семейный"),
                    ("personal", "Личный"),
                ],
                default="main",
                max_length=30,
                verbose_name="Группа бюджета",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("month", "Месяц"),
                    ("quarter", "Квартал"),
                    ("year", "Год"),
                ],
                default="month",
                max_length=20,
                verbose_name="Тип периода",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(
                default="RUB",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Валюта должна быть указана в формате ISO-кода, например RUB.",
                        regex="^[A-Z]{3}$",
                    ),
                ],
                verbose_name="Валюта",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="kind",
            field=models.CharField(
                choices=[
                    ("expense", "Расходный"),
                    ("income", "Доходный"),
                ],
                default="expense",
                max_length=20,
                verbose_name="Тип бюджета",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="rollover",
            field=models.BooleanField(
                default=False,
                verbose_name="Перенос остатка на следующий период",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="paused",
            field=models.BooleanField(
                default=False,
                verbose_name="На паузе",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Комментарий",
            ),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="unique_budget_category_period_per_user",
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_type__in", ["month", "quarter", "year"])),
                name="budget_period_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["expense", "income"])),
                name="budget_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("category_group__in", ["main", "family", "personal"])),
                name="budget_category_group_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="budget_currency_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "category",
                    "kind",
                    "period_type",
                    "period_start",
                    "period_end",
                ),
                name="unique_budget_kind_category_period",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user", "period_type"], name="idx_budget_user_period_type"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user", "kind"], name="idx_budget_user_kind"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user", "category_group"], name="idx_budget_user_group"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user", "paused"], name="idx_budget_user_paused"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user", "currency"], name="idx_budget_user_currency"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "kind", "period_type", "period_start"],
                name="idx_budget_kind_period",
            ),
        ),
    ]
