# Generated by ChatGPT for BUD-1098 on 2026-05-21

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_initial_tag_name(value: str) -> str:
    return " ".join(value.strip().split()).casefold()


def create_system_tag_groups(apps, schema_editor):
    TagGroup = apps.get_model("finance", "TagGroup")

    for name in ["Покупки", "Доход", "Транспорт", "Разное"]:
        TagGroup.objects.get_or_create(
            is_system=True,
            normalized_name=normalize_initial_tag_name(name),
            defaults={
                "name": name,
                "user": None,
            },
        )


def remove_system_tag_groups(apps, schema_editor):
    TagGroup = apps.get_model("finance", "TagGroup")
    TagGroup.objects.filter(
        is_system=True,
        normalized_name__in=[
            normalize_initial_tag_name(name)
            for name in ["Покупки", "Доход", "Транспорт", "Разное"]
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0013_budget_details_and_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80,
                        verbose_name="Название группы тегов",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        verbose_name="Нормализованное название группы",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        verbose_name="Системная группа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа тегов",
                "verbose_name_plural": "Группы тегов",
                "ordering": ["is_system", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80,
                        verbose_name="Название тега",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        verbose_name="Нормализованное название тега",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4F46E5",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Цвет должен быть указан в HEX-формате, например #4F46E5.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="tag",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать в формах операций",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        verbose_name="Системный тег",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="finance.taggroup",
                        verbose_name="Группа тегов",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег операции",
                "verbose_name_plural": "Теги операций",
                "ordering": ["is_system", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="taggroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")),
                name="tag_group_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="taggroup",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("is_system", True), ("user__isnull", True))
                    | models.Q(("is_system", False), ("user__isnull", False))
                ),
                name="tag_group_owner_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taggroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "normalized_name"),
                name="unique_tag_group_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="taggroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("normalized_name",),
                name="unique_system_tag_group_name",
            ),
        ),
        migrations.AddIndex(
            model_name="taggroup",
            index=models.Index(
                fields=["user", "name"],
                name="idx_tag_group_user_name",
            ),
        ),
        migrations.AddIndex(
            model_name="taggroup",
            index=models.Index(
                fields=["user", "is_system"],
                name="idx_tag_group_user_system",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")),
                name="tag_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__regex", "^#[0-9A-Fa-f]{6}$")),
                name="tag_color_hex_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(("icon__regex", "\\S")),
                name="tag_icon_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("is_system", True), ("user__isnull", True))
                    | models.Q(("is_system", False), ("user__isnull", False))
                ),
                name="tag_owner_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "normalized_name"),
                name="unique_tag_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("normalized_name",),
                name="unique_system_tag_name",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user"], name="idx_tag_user"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "group"], name="idx_tag_user_group"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "is_visible"], name="idx_tag_user_visible"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "normalized_name"], name="idx_tag_user_norm_name"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "created_at"], name="idx_tag_user_created"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["is_system"], name="idx_tag_system"),
        ),
        migrations.RunPython(create_system_tag_groups, remove_system_tag_groups),
    ]
