# Generated by ChatGPT for BUD-1099 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_tag_groups_and_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                to="finance.tag",
                verbose_name="Теги операции",
            ),
        ),
    ]
