# Generated by ChatGPT for BUD-1105 on 2026-05-21

import decimal
import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0015_transaction_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        verbose_name="Название шаблона",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=120,
                        verbose_name="Нормализованное название шаблона",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("0.01"),
                            )
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Валюта должна быть указана в формате ISO-кода, например RUB.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активный"), ("archived", "В архиве")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус шаблона",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="Шаблон по умолчанию",
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Количество использований",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего использования",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_templates",
                        to="finance.account",
                        verbose_name="Счёт",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_templates",
                        to="finance.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transaction_templates",
                        to="finance.tag",
                        verbose_name="Теги шаблона",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон операции",
                "verbose_name_plural": "Шаблоны операций",
                "ordering": ["status", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")),
                name="transaction_template_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="transaction_template_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["income", "expense"])),
                name="transaction_template_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])),
                name="transaction_template_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="transaction_template_currency_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "normalized_name"),
                name="unique_active_transaction_template_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("status", "active")),
                fields=("user", "kind"),
                name="unique_default_transaction_template_per_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user"], name="idx_tx_tpl_user"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "status"], name="idx_tx_tpl_user_status"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "kind"], name="idx_tx_tpl_user_kind"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "category"], name="idx_tx_tpl_user_category"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "account"], name="idx_tx_tpl_user_account"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "normalized_name"], name="idx_tx_tpl_user_norm_name"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "use_count"], name="idx_tx_tpl_user_use_count"),
        ),
        migrations.AddIndex(
            model_name="transactiontemplate",
            index=models.Index(fields=["user", "last_used_at"], name="idx_tx_tpl_user_last_used"),
        ),
    ]
