# Generated by ChatGPT for BUD-1108 on 2026-05-21

import apps.finance.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0016_transaction_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Уведомления о бюджетах и целях включены",
                    ),
                ),
                (
                    "thresholds_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Пороговые уведомления включены",
                    ),
                ),
                (
                    "thresholds",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_budget_notification_thresholds,
                        verbose_name="Пороги бюджета",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_budget_notification_events,
                        verbose_name="Типы событий",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_budget_notification_channels,
                        verbose_name="Каналы доставки",
                    ),
                ),
                (
                    "anti_spam",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_budget_notification_anti_spam,
                        verbose_name="Защита от дублей и спама",
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        blank=True,
                        default=apps.finance.models.default_budget_notification_goals,
                        verbose_name="Настройки уведомлений по целям",
                    ),
                ),
                (
                    "preview_usage_percent",
                    models.PositiveSmallIntegerField(
                        default=87,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Процент использования бюджета для предпросмотра",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений о бюджете",
                "verbose_name_plural": "Настройки уведомлений о бюджете",
                "ordering": ["user_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="budgetnotificationsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(preview_usage_percent__gte=0)
                & models.Q(preview_usage_percent__lte=100),
                name="budget_notif_preview_percent_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationsettings",
            index=models.Index(fields=["enabled"], name="idx_budget_notif_enabled"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationsettings",
            index=models.Index(fields=["thresholds_enabled"], name="idx_budget_notif_thresholds"),
        ),
    ]
