# Generated by ChatGPT for BUD-1110

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0017_budget_notification_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetNotificationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("event_type", models.CharField(choices=[("budget_near_limit", "Бюджет: приближение к лимиту"), ("budget_exceeded", "Бюджет: превышение лимита"), ("budget_back_to_normal", "Бюджет: возврат в норму"), ("goal_milestone", "Цель: достигнут промежуточный рубеж"), ("goal_reached", "Цель: цель выполнена"), ("goal_lagging", "Цель: отставание от плана")], max_length=50, verbose_name="Тип события")),
                ("related_object_type", models.CharField(choices=[("transaction", "Операция"), ("goal", "Цель"), ("budget", "Бюджет")], max_length=20, verbose_name="Тип связанного объекта")),
                ("related_object_id", models.PositiveBigIntegerField(verbose_name="ID связанного объекта")),
                ("threshold_id", models.CharField(blank=True, max_length=50, verbose_name="ID порога")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок события")),
                ("message", models.TextField(blank=True, verbose_name="Текст события")),
                ("icon", models.CharField(default="bell", max_length=50, verbose_name="Иконка")),
                ("icon_tone", models.CharField(choices=[("primary", "Основной"), ("success", "Успех"), ("warning", "Предупреждение"), ("error", "Ошибка"), ("info", "Информация")], default="primary", max_length=20, verbose_name="Тон иконки")),
                ("status", models.CharField(choices=[("generated", "Сформировано"), ("delivered", "Доставлено"), ("skipped", "Пропущено")], default="generated", max_length=20, verbose_name="Статус события")),
                ("deduplication_key", models.CharField(max_length=255, verbose_name="Ключ защиты от дублей")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Данные события")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budget_notification_events", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Событие бюджетного уведомления",
                "verbose_name_plural": "События бюджетных уведомлений",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="budgetnotificationevent",
            constraint=models.CheckConstraint(condition=models.Q(("event_type__in", ["budget_near_limit", "budget_exceeded", "budget_back_to_normal", "goal_milestone", "goal_reached", "goal_lagging"])), name="budget_notif_event_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="budgetnotificationevent",
            constraint=models.CheckConstraint(condition=models.Q(("related_object_type__in", ["transaction", "goal", "budget"])), name="budget_notif_event_obj_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="budgetnotificationevent",
            constraint=models.CheckConstraint(condition=models.Q(("icon_tone__in", ["primary", "success", "warning", "error", "info"])), name="budget_notif_event_tone_valid"),
        ),
        migrations.AddConstraint(
            model_name="budgetnotificationevent",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["generated", "delivered", "skipped"])), name="budget_notif_event_status_valid"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["user"], name="idx_bn_event_user"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["user", "event_type"], name="idx_bn_event_user_type"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["user", "related_object_type", "related_object_id"], name="idx_bn_event_object"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["user", "deduplication_key"], name="idx_bn_event_dedup"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["user", "created_at"], name="idx_bn_event_created"),
        ),
        migrations.AddIndex(
            model_name="budgetnotificationevent",
            index=models.Index(fields=["status"], name="idx_bn_event_status"),
        ),
    ]
