from __future__ import annotations

RECOMMENDATIONS_TAG = "finance-recommendations"

RECOMMENDATION_GENERATION_MODE_RULE_BASED = "rule_based"
RECOMMENDATION_GENERATION_MODE_ML = "ml"

RECOMMENDATION_TYPE_BUDGET = "budget"
RECOMMENDATION_TYPE_SAVING = "saving"
RECOMMENDATION_TYPE_GOAL = "goal"
RECOMMENDATION_TYPE_CASHFLOW = "cashflow"
RECOMMENDATION_TYPE_PLANNED_PAYMENT = "planned_payment"
RECOMMENDATION_TYPE_EXPENSE_STABILITY = "expense_stability"
RECOMMENDATION_TYPE_ONBOARDING = "onboarding"
RECOMMENDATION_TYPE_FINANCIAL_HEALTH = "financial_health"

RECOMMENDATION_TYPES = [
    RECOMMENDATION_TYPE_BUDGET,
    RECOMMENDATION_TYPE_SAVING,
    RECOMMENDATION_TYPE_GOAL,
    RECOMMENDATION_TYPE_CASHFLOW,
    RECOMMENDATION_TYPE_PLANNED_PAYMENT,
    RECOMMENDATION_TYPE_EXPENSE_STABILITY,
    RECOMMENDATION_TYPE_ONBOARDING,
    RECOMMENDATION_TYPE_FINANCIAL_HEALTH,
]

RECOMMENDATION_STATUS_NEW = "new"
RECOMMENDATION_STATUS_ACTIVE = "active"
RECOMMENDATION_STATUS_ACCEPTED = "accepted"
RECOMMENDATION_STATUS_HIDDEN = "hidden"
RECOMMENDATION_STATUS_SNOOZED = "snoozed"
RECOMMENDATION_STATUS_EXPIRED = "expired"

RECOMMENDATION_STATUSES = [
    RECOMMENDATION_STATUS_NEW,
    RECOMMENDATION_STATUS_ACTIVE,
    RECOMMENDATION_STATUS_ACCEPTED,
    RECOMMENDATION_STATUS_HIDDEN,
    RECOMMENDATION_STATUS_SNOOZED,
    RECOMMENDATION_STATUS_EXPIRED,
]

RECOMMENDATION_VISIBLE_STATUSES = [
    RECOMMENDATION_STATUS_NEW,
    RECOMMENDATION_STATUS_ACTIVE,
    RECOMMENDATION_STATUS_SNOOZED,
]

RECOMMENDATION_PRIORITY_HIGH = "high"
RECOMMENDATION_PRIORITY_MEDIUM = "medium"
RECOMMENDATION_PRIORITY_LOW = "low"

RECOMMENDATION_PRIORITIES = [
    RECOMMENDATION_PRIORITY_HIGH,
    RECOMMENDATION_PRIORITY_MEDIUM,
    RECOMMENDATION_PRIORITY_LOW,
]

RECOMMENDATION_PRIORITY_ORDER = {
    RECOMMENDATION_PRIORITY_HIGH: 1,
    RECOMMENDATION_PRIORITY_MEDIUM: 2,
    RECOMMENDATION_PRIORITY_LOW: 3,
}

RECOMMENDATION_ACTION_VIEW = "view"
RECOMMENDATION_ACTION_ACCEPT = "accept"
RECOMMENDATION_ACTION_HIDE = "hide"
RECOMMENDATION_ACTION_SNOOZE = "snooze"
RECOMMENDATION_ACTION_REFRESH = "refresh"

RECOMMENDATION_ACTIONS = [
    RECOMMENDATION_ACTION_VIEW,
    RECOMMENDATION_ACTION_ACCEPT,
    RECOMMENDATION_ACTION_HIDE,
    RECOMMENDATION_ACTION_SNOOZE,
    RECOMMENDATION_ACTION_REFRESH,
]

RECOMMENDATION_EVENT_CREATED = "created"
RECOMMENDATION_EVENT_VIEWED = "viewed"
RECOMMENDATION_EVENT_ACCEPTED = "accepted"
RECOMMENDATION_EVENT_HIDDEN = "hidden"
RECOMMENDATION_EVENT_SNOOZED = "snoozed"
RECOMMENDATION_EVENT_EXPIRED = "expired"
RECOMMENDATION_EVENT_REFRESHED = "refreshed"

RECOMMENDATION_EVENTS = [
    RECOMMENDATION_EVENT_CREATED,
    RECOMMENDATION_EVENT_VIEWED,
    RECOMMENDATION_EVENT_ACCEPTED,
    RECOMMENDATION_EVENT_HIDDEN,
    RECOMMENDATION_EVENT_SNOOZED,
    RECOMMENDATION_EVENT_EXPIRED,
    RECOMMENDATION_EVENT_REFRESHED,
]

RECOMMENDATION_SOURCE_FINANCIAL_HEALTH = "financial_health"
RECOMMENDATION_SOURCE_BUDGETS = "budgets"
RECOMMENDATION_SOURCE_GOALS = "goals"
RECOMMENDATION_SOURCE_TRANSACTIONS = "transactions"
RECOMMENDATION_SOURCE_PLANNED_TRANSACTIONS = "planned_transactions"
RECOMMENDATION_SOURCE_ONBOARDING = "onboarding"

RECOMMENDATION_SOURCES = [
    RECOMMENDATION_SOURCE_FINANCIAL_HEALTH,
    RECOMMENDATION_SOURCE_BUDGETS,
    RECOMMENDATION_SOURCE_GOALS,
    RECOMMENDATION_SOURCE_TRANSACTIONS,
    RECOMMENDATION_SOURCE_PLANNED_TRANSACTIONS,
    RECOMMENDATION_SOURCE_ONBOARDING,
]

RECOMMENDATION_CODE_CREATE_BUDGET = "create_budget"
RECOMMENDATION_CODE_REDUCE_UNSTABLE_EXPENSES = "reduce_unstable_expenses"
RECOMMENDATION_CODE_INCREASE_SAVINGS_RATE = "increase_savings_rate"
RECOMMENDATION_CODE_CREATE_EMERGENCY_FUND_GOAL = "create_emergency_fund_goal"
RECOMMENDATION_CODE_REVIEW_PLANNED_PAYMENTS = "review_planned_payments"
RECOMMENDATION_CODE_FIX_CASH_GAP_RISK = "fix_cash_gap_risk"
RECOMMENDATION_CODE_COMPLETE_ONBOARDING = "complete_onboarding"
RECOMMENDATION_CODE_CHECK_BUDGET_OVERRUN = "check_budget_overrun"

RECOMMENDATION_CODES = [
    RECOMMENDATION_CODE_CREATE_BUDGET,
    RECOMMENDATION_CODE_REDUCE_UNSTABLE_EXPENSES,
    RECOMMENDATION_CODE_INCREASE_SAVINGS_RATE,
    RECOMMENDATION_CODE_CREATE_EMERGENCY_FUND_GOAL,
    RECOMMENDATION_CODE_REVIEW_PLANNED_PAYMENTS,
    RECOMMENDATION_CODE_FIX_CASH_GAP_RISK,
    RECOMMENDATION_CODE_COMPLETE_ONBOARDING,
    RECOMMENDATION_CODE_CHECK_BUDGET_OVERRUN,
]

RECOMMENDATION_DEFAULT_STATUS = RECOMMENDATION_STATUS_ACTIVE
RECOMMENDATION_DEFAULT_PRIORITY = RECOMMENDATION_PRIORITY_MEDIUM
RECOMMENDATION_DEFAULT_TTL_DAYS = 30
RECOMMENDATION_SNOOZE_DEFAULT_DAYS = 7
RECOMMENDATION_MAX_ACTIVE_PER_USER = 20
