# Generated by Django 5.2.14 on 2026-05-14 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True, verbose_name='Hash token')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес запроса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Token восстановления пароля',
                'verbose_name_plural': 'Tokens восстановления пароля',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='users_passw_token_h_97b790_idx'), models.Index(fields=['user', 'used_at'], name='users_passw_user_id_43c017_idx'), models.Index(fields=['expires_at'], name='users_passw_expires_853bc2_idx')],
            },
        ),
    ]
