# Generated by ChatGPT on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Отчество",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=32,
                verbose_name="Телефон",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                verbose_name="Краткое описание",
            ),
        ),
    ]
