# Generated by ChatGPT for BUD-1117

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.users.models.user_avatar_upload_to,
                verbose_name="Аватар",
            ),
        ),
    ]
