# Generated by ChatGPT for BUD-1118

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("profile_updated", "Профиль обновлён"), ("name_changed", "ФИО изменено"), ("email_changed", "Email изменён"), ("phone_changed", "Телефон изменён"), ("city_changed", "Город изменён"), ("bio_changed", "Описание изменено"), ("avatar_uploaded", "Аватар загружен"), ("avatar_deleted", "Аватар удалён")], max_length=40, verbose_name="Действие")),
                ("changed_fields", models.JSONField(blank=True, default=list, verbose_name="Изменённые поля")),
                ("old_values", models.JSONField(blank=True, default=dict, verbose_name="Старые значения")),
                ("new_values", models.JSONField(blank=True, default=dict, verbose_name="Новые значения")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Метаданные")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_audit_logs", to="users.user", verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Аудит профиля пользователя",
                "verbose_name_plural": "Аудит профилей пользователей",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="userprofileauditlog",
            index=models.Index(fields=["user", "created_at"], name="idx_prof_audit_user_time"),
        ),
        migrations.AddIndex(
            model_name="userprofileauditlog",
            index=models.Index(fields=["action"], name="idx_prof_audit_action"),
        ),
    ]
