# Generated by ChatGPT for BUD-1120

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_profile_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAppSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timezone", models.CharField(default="Asia/Krasnoyarsk", max_length=64, verbose_name="Часовой пояс")),
                ("date_format", models.CharField(choices=[("DD.MM.YYYY", "ДД.ММ.ГГГГ"), ("YYYY-MM-DD", "ГГГГ-ММ-ДД"), ("MM/DD/YYYY", "ММ/ДД/ГГГГ")], default="DD.MM.YYYY", max_length=20, verbose_name="Формат даты")),
                ("number_format", models.CharField(choices=[("ru-RU", "Русский формат"), ("en-US", "Английский формат")], default="ru-RU", max_length=20, verbose_name="Формат чисел")),
                ("default_currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта по умолчанию")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="app_settings", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Настройки приложения пользователя",
                "verbose_name_plural": "Настройки приложения пользователей",
            },
        ),
        migrations.AddIndex(
            model_name="userappsettings",
            index=models.Index(fields=["user"], name="idx_appset_user"),
        ),
        migrations.AddIndex(
            model_name="userappsettings",
            index=models.Index(fields=["default_currency"], name="idx_appset_currency"),
        ),
    ]
