# Generated by Django 5.2.14 on 2026-06-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_phone_verification_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
