# Generated by ChatGPT for Cloudinary avatar storage

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_sync_user_model_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=700, verbose_name="URL аватара"),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_public_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Cloudinary public ID аватара"),
        ),
    ]
