# Generated by ChatGPT for BUD-1056

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_cloudinary_avatar_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSurvey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("not_started", "Не начат"), ("in_progress", "В процессе"), ("completed", "Завершён"), ("failed", "Ошибка")], default="not_started", max_length=20, verbose_name="Статус onboarding")),
                ("answers", models.JSONField(blank=True, default=dict, verbose_name="Ответы пользователя")),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="Результат применения onboarding")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата начала")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_survey", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Onboarding-анкета пользователя",
                "verbose_name_plural": "Onboarding-анкеты пользователей",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="onboardingsurvey",
            index=models.Index(fields=["status"], name="idx_onboard_status"),
        ),
        migrations.AddIndex(
            model_name="onboardingsurvey",
            index=models.Index(fields=["completed_at"], name="idx_onboard_completed"),
        ),
        migrations.AddIndex(
            model_name="onboardingsurvey",
            index=models.Index(fields=["created_at"], name="idx_onboard_created"),
        ),
    ]
