# Generated by ChatGPT for BUD-1133

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PwaNotificationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("push_enabled", models.BooleanField(default=True, verbose_name="Push-уведомления включены")),
                ("sync_conflict", models.BooleanField(default=True, verbose_name="Уведомлять о конфликтах синхронизации")),
                ("sync_failed", models.BooleanField(default=True, verbose_name="Уведомлять об ошибках синхронизации")),
                ("budget_limit_warning", models.BooleanField(default=True, verbose_name="Уведомлять о приближении к лимиту бюджета")),
                ("planned_transaction_due", models.BooleanField(default=True, verbose_name="Уведомлять о планируемых операциях")),
                ("receipt_imported", models.BooleanField(default=True, verbose_name="Уведомлять об импорте чека")),
                ("quiet_hours_enabled", models.BooleanField(default=False, verbose_name="Тихие часы включены")),
                ("quiet_hours_from", models.TimeField(default=datetime.time(22, 0), verbose_name="Начало тихих часов")),
                ("quiet_hours_to", models.TimeField(default=datetime.time(8, 0), verbose_name="Окончание тихих часов")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pwa_notification_settings", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "PWA настройки уведомлений",
                "verbose_name_plural": "PWA настройки уведомлений",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="PwaPushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=120, verbose_name="ID устройства")),
                ("provider", models.CharField(choices=[("web_push", "Web Push")], default="web_push", max_length=30, verbose_name="Push-провайдер")),
                ("endpoint", models.URLField(max_length=2048, verbose_name="Push endpoint")),
                ("p256dh", models.TextField(verbose_name="Ключ p256dh")),
                ("auth", models.TextField(verbose_name="Auth secret")),
                ("browser", models.CharField(blank=True, max_length=80, verbose_name="Браузер")),
                ("platform", models.CharField(blank=True, max_length=80, verbose_name="Платформа")),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Последнее использование")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата отзыва")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pwa_push_subscriptions", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "PWA push-подписка",
                "verbose_name_plural": "PWA push-подписки",
                "ordering": ["-is_active", "-updated_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="pwanotificationsettings",
            index=models.Index(fields=["user"], name="idx_pwa_notif_set_user"),
        ),
        migrations.AddIndex(
            model_name="pwanotificationsettings",
            index=models.Index(fields=["push_enabled"], name="idx_pwa_notif_push"),
        ),
        migrations.AddConstraint(
            model_name="pwapushsubscription",
            constraint=models.UniqueConstraint(fields=("user", "endpoint"), name="unique_pwa_push_endpoint_per_user"),
        ),
        migrations.AddConstraint(
            model_name="pwapushsubscription",
            constraint=models.CheckConstraint(condition=models.Q(provider__in=["web_push"]), name="pwa_push_provider_valid"),
        ),
        migrations.AddIndex(
            model_name="pwapushsubscription",
            index=models.Index(fields=["user", "is_active"], name="idx_pwa_push_user_active"),
        ),
        migrations.AddIndex(
            model_name="pwapushsubscription",
            index=models.Index(fields=["user", "device_id"], name="idx_pwa_push_user_device"),
        ),
        migrations.AddIndex(
            model_name="pwapushsubscription",
            index=models.Index(fields=["user", "updated_at"], name="idx_pwa_push_user_updated"),
        ),
    ]
